### ISSUE TITLE
background:'transparent' not working correctly

### ISSUE THREAD

**Issue by sorashin** [emilwidlund/framer-form#2]
Hi, I tried to float a white box in the orange background but Scene's transparent background property is not working correctly. (line 67: circle.background = "transparent")

Here is my framer file.
https://framer.cloud/DYERS

**Comment by emilwidlund** [comment]
Make sure to use the "backgroundColor"-property instead.

Remove line 18 and replace 'background' with 'backgroundColor' on line 67.

**Comment by emilwidlund** [comment]
I just realised that the documentation specified "background" as the property. I've now updated it to reflect 'backgroundColor' instead.

Thanks.
