### ISSUE TITLE
model.animate does not work

### ISSUE THREAD

**Issue by emilwidlund** [emilwidlund/framer-form#3]
Animate-method returns "Animation is not a constructor"-error.

**Comment by emilwidlund** [comment]
Fixed in 5407e9e.

**Comment by Oscarnilsson** [comment]
![image](https://user-images.githubusercontent.com/5172141/38816811-3a0246b0-4197-11e8-8666-53ece4c89e65.png)

Possibly running into the same error here ☝️

**Comment by emilwidlund** [comment]
Make sure to reinstall the module and it should work for you 😊
